export const CONNECTION_UPDATE_VALUE = 'CONNECTION_UPDATE_VALUE';
export const AUTHENTICATION_UPDATE_VALUE = 'AUTHENTICATION_UPDATE_VALUE';
export const USER_CONNECTED_UPDATE_VALUE = 'USER_CONNECTED_UPDATE_VALUE';